version: '2'

services:
  angular-project:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    container_name: angular-project-container
    image: angular-project
    networks:
      - dev-network
    ports:
      - '4200:80'

  json-api:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: angular-api-container
    image: angular-api
    networks:
      - dev-network
    ports:
      - '3000:3000'

  web-oidc:
    build:
      context: ./oidc
      dockerfile: ./Dockerfile
    container_name: angular-oidc-container
    image: node-oidc
    networks:
      - dev-network
    ports:
      - '5000:5000'

networks:
  dev-network:
    driver: bridge
